development:
  adapter: postgresql
  database: jukebox_development
  host: localhost
  username:
  password:
  min_messages: warning

test:
  adapter: postgresql
  database: jukebox_test
  host: localhost
  username:
  password:
  min_messages: warning

production:
  adapter: postgresql
  database:
  host:
  username:
  password:
  min_messages: warning
